services:
  # Frontend
  - type: web
    name: gamilist-web
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://gamilist-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free

  # Backend
  - type: web
    name: gamilist-api
    runtime: node
    plan: free
    region: ohio
    buildCommand: npm ci
    startCommand: node api/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gamilist-db
          property: connectionString
      - key: TWITCH_CLIENT_ID
        sync: false   # add value in Render dashboard
      - key: TWITCH_CLIENT_SECRET
        sync: false   # add value in Render dashboard
databases:
  - name: gamilist-db
    plan: free
    region: ohio
    postgresMajorVersion: "17"
